CCIA/Areas/Admin/Models/OECD/EditCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CCIA.Helpers;
using System.ComponentModel.DataAnnotations;
using CCIA.Services;

namespace CCIA.Models
{   
     
    public class AdminOECDEditCreateViewModel
    {
        public OECD oecd { get; set; } 
        
       public List<AbbrevOECDClass> classes { get; set; }

       public List<Countries> countries { get; set; }
               
        public static async Task<AdminOECDEditCreateViewModel> Create(CCIAContext _dbContext, IFullCallService _helper , int id)
        {       
            var thisoecd = await _helper.FullOECD().Where(o => o.Id == id).FirstOrDefaultAsync();            
                       
            var model = new AdminOECDEditCreateViewModel
            {
                oecd = thisoecd,
                classes = await _dbContext.AbbrevOECDClass.OrderBy(x => x.SortOrder).ToListAsync(),
                countries = await _dbContext.Countries.OrderBy(x => x.Name).ToListAsync(),
            };

            return model;
        }

        
    }    
    
}

CCIA/Areas/Admin/Controllers/OECDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCIA.Services;
using CCIA.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CCIA.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using CCIA.Models.DetailsViewModels;
using System.Security.Claims;
using CCIA.Helpers;
using Microsoft.Data.SqlClient;

namespace CCIA.Controllers.Admin
{

    public class OECDController : AdminController
    {
        private readonly CCIAContext _dbContext;
        private readonly IFullCallService _helper;
        private readonly INotificationService _notificationService;

        public OECDController(CCIAContext dbContext, IFullCallService helper, INotificationService notificationService)
        {
            _dbContext = dbContext;
            _helper = helper;
            _notificationService = notificationService;
        }

        public ActionResult Index ()
        {
            return View();
        }

         public ActionResult Lookup()
        {
            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            var oecd = _helper.FullOECD();
            var model = await oecd.Where(o => o.Id == id).FirstOrDefaultAsync();
            return View(model);
        }

        public async Task<IActionResult> Previous(int id)
        {
            var previousId = await _dbContext.OECD.Where(x => x.Id < id).OrderBy(x => x.Id).Select(x => x.Id).LastOrDefaultAsync();
            return RedirectToAction(nameof(Details), new {id = previousId});
        }

        public async Task<IActionResult> Next(int id)
        {
            var previousId = await _dbContext.OECD.Where(x => x.Id > id).OrderBy(x => x.Id).Select(x => x.Id).FirstOrDefaultAsync();
            return RedirectToAction(nameof(Details), new {id = previousId});
        }

        public async Task<IActionResult> Create()
        {
            var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, 0);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AdminOECDEditCreateViewModel vm)
        {   
            var oecdToCreate = new OECD();            
            var create = vm.oecd;
            var seed = await _dbContext.Seeds.Include(s => s.Variety).Where(s => s.Id == create.SeedsId).FirstAsync();

            if(seed == null)
            {
                ErrorMessage = "SID not found in database";
                var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, 0);
                return View(model); 
            }
            oecdToCreate.SeedsId = create.SeedsId;
            oecdToCreate.VarietyId = seed.OfficialVarietyId;            
            oecdToCreate.Pounds = create.Pounds;
            oecdToCreate.CertNumber = string.IsNullOrWhiteSpace(create.CertNumber) ? seed.CertNumber : create.CertNumber;
            oecdToCreate.ClassId = create.ClassId;
            oecdToCreate.CloseDate = create.CloseDate;
            oecdToCreate.ShipperId = create.ShipperId;
            oecdToCreate.ConditionerId = create.ConditionerId;
            oecdToCreate.CountryId = create.CountryId;
            oecdToCreate.LotNumber = string.IsNullOrWhiteSpace(create.LotNumber) ? seed.LotNumber : create.LotNumber;
            oecdToCreate.DateRequested = DateTime.Now;
            oecdToCreate.NotCertified = create.NotCertified;
            oecdToCreate.Canceled = false;
            oecdToCreate.DataEntryDate = DateTime.Now;
            oecdToCreate.DataEntryUser = User.FindFirstValue(ClaimTypes.Name);
            oecdToCreate.DomesticOrigin = create.DomesticOrigin;
            oecdToCreate.ReferenceNumber = create.ReferenceNumber;
            oecdToCreate.USDAReported = false;
            oecdToCreate.TagsRequested = create.TagsRequested;
            oecdToCreate.OECDNumber = GetInitialOECDNumber(seed.CertYear.Value, seed.CertNumber, seed.LotNumber);

            if(ModelState.IsValid){
                _dbContext.Add(oecdToCreate);
                await _dbContext.SaveChangesAsync();
                Message = "OECD Create";
            } else {
                ErrorMessage = "Something went wrong.";
                var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, 0);
                return View(model); 
            }

            return RedirectToAction(nameof(Details), new { id = oecdToCreate.Id });  

        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, id);
            return View(model);
        }        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AdminOECDEditCreateViewModel vm)
        {   
            var oecdToUpdate = await _dbContext.OECD.Where(a => a.Id == id).FirstAsync();
            var edit = vm.oecd;
            oecdToUpdate.UpdateDate = DateTime.Now;
            oecdToUpdate.UpdateUser = User.FindFirstValue(ClaimTypes.Name);
            oecdToUpdate.SeedsId = edit.SeedsId;
            oecdToUpdate.BID = edit.BID;
            oecdToUpdate.CloseDate = edit.CloseDate;
            oecdToUpdate.ShipperId = edit.ShipperId;
            oecdToUpdate.ConditionerId = edit.ConditionerId;
            oecdToUpdate.CertNumber = edit.CertNumber;
            oecdToUpdate.LotNumber = edit.LotNumber;
            oecdToUpdate.TagsRequested = edit.TagsRequested;
            oecdToUpdate.ClassId = edit.ClassId;
            oecdToUpdate.Pounds = edit.Pounds;
            oecdToUpdate.VarietyId = edit.VarietyId;
            oecdToUpdate.ReferenceNumber = edit.ReferenceNumber;
            oecdToUpdate.CountryId = edit.CountryId;
            oecdToUpdate.DomesticOrigin = edit.DomesticOrigin;
            oecdToUpdate.NotCertified = edit.NotCertified;
            oecdToUpdate.Canceled = edit.Canceled;
            oecdToUpdate.Comments = edit.Comments;
            oecdToUpdate.AdminComments = edit.AdminComments;
            oecdToUpdate.OECDNumber = edit.OECDNumber;

            if(ModelState.IsValid){
                await _dbContext.SaveChangesAsync();
                Message = "OECD Updated";
            } else {
                if(ModelState.ErrorCount ==1)
                {
                    foreach(var modelStateKey in ViewData.ModelState.Keys)
                    {
                        var modelStateVal = ViewData.ModelState[modelStateKey];
                        foreach(var error in modelStateVal.Errors)
                        {
                            var key = modelStateKey;
                            if(key == "oecd.Variety.Name")
                            {
                                await _dbContext.SaveChangesAsync();
                                Message = "OECD Updated";
                                return RedirectToAction(nameof(Details), new { id = oecdToUpdate.Id }); 
                            }
                        }
                    }                    
                    
                }
                ErrorMessage = "Something went wrong.";
                var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, id);
                return View(model); 
            }

            return RedirectToAction(nameof(Details), new { id = oecdToUpdate.Id });  

        }

        public async Task<IActionResult> ToggleFollowup(int id)
        {
            var oecdToToggle = await _dbContext.OECD.Where(a => a.Id == id).FirstOrDefaultAsync();
            if(oecdToToggle == null)
            {
                ErrorMessage = "OECD File not found";
                return RedirectToAction(nameof(Index));
            }
            oecdToToggle.FollowUp = !oecdToToggle.FollowUp;
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new {id = id});
        }

        public async Task<IActionResult> Certificate(int id, bool charge)
        {
            var oecd = _helper.FullOECD();
            var model = await oecd.Where(o => o.Id == id).FirstOrDefaultAsync();

            if(charge)
            {
                if(model.DatePrinted == null)
                {
                    await _notificationService.OECDCharged(model);
                    model.DatePrinted = DateTime.Now;
                    model.UpdateUser = User.FindFirstValue(ClaimTypes.Name);
                    await _dbContext.SaveChangesAsync();
                }
                var p0 = new SqlParameter("@file_num", model.Id);
                await _dbContext.Database.ExecuteSqlRawAsync($"EXEC charge_OECD @file_num", p0);
            }
            return View(model);
        }

        public ActionResult GetListToPrint()
        {
            return View();
        }

        public async Task<IActionResult> Certificates(string ids)
        {           
            var listIds = ids.Split(',').Select(int.Parse).ToList();
            var oecd = _helper.FullOECD();
            var model = await oecd.Where(o => listIds.Contains(o.Id)).ToListAsync();           
            return View(model);
        }

        public async Task<IActionResult> Invoice(int id)
        {
            var oecd = _helper.FullOECD();
            var model = await oecd.Where(o => o.Id == id).FirstOrDefaultAsync();

            return View(model);
        }

        public async Task<IActionResult> Search()
        {
            var model = await AdminOECDSearchViewModel.Create(_dbContext, null);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(AdminOECDSearchViewModel vm)
        {
            var model = await AdminOECDSearchViewModel.Create(_dbContext, vm);
            return View(model);
        }

        public async Task<ActionResult> ReportingSheets()

CCIA/Areas/Client/Controllers/OECDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCIA.Helpers;
using CCIA.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CCIA.Models.IndexViewModels;
using CCIA.Services;

namespace CCIA.Controllers.Client
{
    public class OECDController : ClientController
    {
        private readonly CCIAContext _dbContext;
        private readonly IFullCallService _helper;
		private readonly INotificationService _notification;

		public OECDController(CCIAContext dbContext, IFullCallService helper, INotificationService notification)
        {
            _dbContext = dbContext;
            _helper = helper;
			_notification = notification;
		}

        
        // GET: Application
        public async Task<IActionResult> Index(int certYear)
        { 
            var orgId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value);
            int? certYearToUse;
            if (certYear == 0)
            {
                certYearToUse = await _dbContext.OECD.Where(o => o.ConditionerId == orgId).MaxAsync(x => (int?)x.DataEntryDate.Value.Year);
            } else
            {
                certYearToUse = certYear;
            }
            if(certYearToUse == null)
            {
                certYearToUse = CertYearFinder.CertYear;
            }
            
            var model = await OECDIndexViewModel.Create(_dbContext, orgId, certYearToUse.Value);            
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, id);
            if(model == null)
            {
                ErrorMessage = "OECD record not found";
                return RedirectToAction("Index");
            }
            if (model.oecd.ConditionerId != int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value))
            {
                ErrorMessage = "You are not the conditioner for that OECD record! Access denied.";
                return RedirectToAction(nameof(Index));
            }
            if (model.oecd.DatePrinted.HasValue)
            {
                ErrorMessage = "OECD Certificate marked complete by CCIA staff. No edits allowed.";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AdminOECDEditCreateViewModel vm)
        {
            var oecdEdit = vm.oecd;
            var oecdToUpdate = await _dbContext.OECD.Where(o => o.Id == id).FirstOrDefaultAsync();
			if (oecdToUpdate == null)
			{
				ErrorMessage = "OECD record not found";
				return RedirectToAction("Index");
			}
			if (oecdToUpdate.ConditionerId != int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value))
			{
				ErrorMessage = "You are not the conditioner for that OECD record! Access denied.";
				return RedirectToAction(nameof(Index));
			}
			if (oecdToUpdate.DatePrinted.HasValue)
			{
				ErrorMessage = "OECD Certificate marked complete by CCIA staff. No edits allowed.";
				return RedirectToAction(nameof(Index));
			}

            oecdToUpdate.UpdateUser = User.Claims.FirstOrDefault(c => c.Type == "contactId").Value;
            oecdToUpdate.UpdateDate = DateTime.Now;
            oecdToUpdate.CloseDate = oecdEdit.CloseDate;
            oecdToUpdate.CountryId = oecdEdit.CountryId;
            oecdToUpdate.Pounds = oecdEdit.Pounds;
            oecdToUpdate.ClassId = oecdEdit.ClassId;
            oecdToUpdate.Comments = oecdEdit.Comments;
            oecdToUpdate.TagsRequested = oecdEdit.TagsRequested;

			if (ModelState.IsValid)
			{
                await _notification.OECDClientUpated(oecdToUpdate);
				await _dbContext.SaveChangesAsync();
				Message = "OECD Updated";
			}
			else
			{
				if (ModelState.ErrorCount == 1)
				{
					foreach (var modelStateKey in ViewData.ModelState.Keys)
					{
						var modelStateVal = ViewData.ModelState[modelStateKey];
						foreach (var error in modelStateVal.Errors)
						{
							var key = modelStateKey;
							if (key == "oecd.Variety.Name")
							{
                                await _notification.OECDClientUpated(oecdToUpdate);
								await _dbContext.SaveChangesAsync();								
								Message = "OECD Updated";
								return RedirectToAction(nameof(Edit), new { id = oecdToUpdate.Id });
							}
						}
					}
				}
				ErrorMessage = "Something went wrong.";
				var model = await AdminOECDEditCreateViewModel.Create(_dbContext, _helper, id);
				return View(model);
			}
			return RedirectToAction(nameof(Edit), new { id = oecdToUpdate.Id });
		}

        public async Task<IActionResult> Complete(int id, AdminOECDEditCreateViewModel vm)
        {			
			var oecdToUpdate = await _dbContext.OECD.Where(o => o.Id == vm.oecd.Id).FirstOrDefaultAsync();
			if (oecdToUpdate == null)
			{
				ErrorMessage = "OECD record not found";
				return RedirectToAction("Index");
			}
			if (oecdToUpdate.ConditionerId != int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value))
			{
				ErrorMessage = "You are not the conditioner for that OECD record! Access denied.";
				return RedirectToAction(nameof(Index));
			}
			if (oecdToUpdate.DatePrinted.HasValue)
			{
				ErrorMessage = "OECD Certificate marked complete by CCIA staff. No edits allowed.";
				return RedirectToAction(nameof(Index));
			}
            await _notification.OECDClientComplete(oecdToUpdate);
            await _dbContext.SaveChangesAsync();
            Message = "OECD submitted for final print";
            return RedirectToAction(nameof(Index));
		}


		public async Task<IActionResult> Certificate(int id)
        {
            var oecd = _helper.FullOECD();
            var model = await oecd.Where(o => o.Id == id).FirstOrDefaultAsync();
            if(model.ConditionerId != int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value))
            {
                ErrorMessage = "You are not the conditioner for that certificate! Access denied.";
                return RedirectToAction(nameof(Index));
            }         
            if(model.DatePrinted.HasValue)
            {
                return View("~/Areas/Admin/Views/OECD/Certificate.cshtml",model);
            }   else {
                ErrorMessage = "OECD Certificate not marked complete by CCIA staff. Please check back later.";
                return RedirectToAction(nameof(Index));
            }
             
        }


      
    }
}

CCIA/Areas/Admin/Views/OECD/Certificates.cshtml
@model List<CCIA.Models.OECD>

@{
    Layout = null;
}

<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>OECD Certificate</title>
    <meta http-equiv="content-style-type" content="text/css" />
    <link rel="stylesheet" href="/css/printStyle.css" type="text/css" />
</head>
<body>    
    @foreach(var file in Model)
    {
        <div style="page-break-after: always;">
          

            <div>
                <a asp-action="Details" asp-controller="OECD" asp-route-id="@file.Id" class="noprint">Return to OECD</a>
            </div>
            <div>
                <table width="100%" border="0">
                    <tr>
                        <td align="center" width="100%">
                            <div align="center" class="title">
                                @if (!file.DatePrinted.HasValue)
                                {
                                    <span class="warning">This OECD Certificate has not been printed, and therefore the charges may
                                        not be finalized!</span><br>
                                }
                                OECD Certificate Invoice
                            </div>
                            <div align="center">
                                California Crop Improvement Association<br />Frank G. Parsons Seed Certification
                                Center<br />University of California<br />One Shields Avenue<br />Davis, California
                                95616-8541<br />
                                <br />
                            </div>
                        </td>

                    </tr>
                </table>

                <table border="0" width="100%">
                    <tr>
                        <td valign="top">
                            <table width="100%" border="0">
                                <tr>
                                    <td valign="top">Shipper: </td>
                                    <td class="labelnoline">
                                        @file.ShipperOrganization.Name

                                        &nbsp; &nbsp;&nbsp; (ID# @file.ShipperOrganization.Id)
                                    </td>
                                    <td align="right" valign="top" class="labelnoline">
                                        Close Date: @file.CloseDate.Value.ToShortDateString()
                                    </td>
                                </tr>
                                <tr>
                                    <td> </td>
                                    <td colspan="2" class="labelnoline">
                                        @if(file.ShipperOrganization.Addresses != null)
                                        {
                                            @Html.Raw(file.ShipperOrganization.Addresses.First().Address.AddressLines)<br>
                                            @file.ShipperOrganization.Addresses.First().Address.City<span>,</span>
                                            @file.ShipperOrganization.Addresses.First().Address.StateProvince.StateProvinceCode
                                            @file.ShipperOrganization.Addresses.First().Address.PostalCode
                                        }
                                    </td>
                                </tr>
                                <tr>
                                    <td>Conditioner: </td>
                                    <td class="labelnoline">
                                        @file.ConditionerOrganization.Name

                                        &nbsp; &nbsp;&nbsp; (ID# @file.ConditionerOrganization.Id)
                                    </td>
                                </tr>
                                <tr>
                                    <td> </td>
                                    <td colspan="2" class="labelnoline">
                                        @if(file.ConditionerOrganization.Addresses != null)
                                        {
                                            @Html.Raw(file.ConditionerOrganization.Addresses.First().Address.AddressLines)<br>
                                            @file.ConditionerOrganization.Addresses.First().Address.City<span>,</span>
                                            @file.ConditionerOrganization.Addresses.First().Address.StateProvince.StateProvinceCode
                                            @file.ConditionerOrganization.Addresses.First().Address.PostalCode
                                        }
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <br />
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3">
                                        An OECD Certificate/Tags was requested on the following lots.
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <br />
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td>
                                        OECD File Number:&nbsp;</td>
                                    <td colspan="2" class="doublespace">
                                        <span class="lablenoline">@file.Id</span>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td nowrap="noWrap">
                                        Variety and Crop:&nbsp;</td>
                                    <td colspan="2" class="doublespace">
                                        <span class="labelnoline">@file.Variety.Name &nbsp; @file.Variety.Crop.Name</span>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td>
                                        OECD Reference Number:</td>
                                    <td class="labelnoline">
                                        @file.ReferenceNumber
                                    </td>
                                    <td>
                                        Weight of Lot:
                                        <span class="labelnoline">@Html.DisplayFor(x => file.Pounds)</span>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td>
                                        OECD Lot Number:</td>
                                    <td class="labelnoline">
                                        @file.LotReferenceNumber
                                    </td>
                                    <td>
                                        Number of Tags:
                                        <span class="labelnoline">@file.TagsRequested</span>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td>
                                        Class Produced:
                                    </td>
                                    <td class="labelnoline">
                                        @file.Class.Class
                                    </td>
                                    <td>@file.LinkTitle: <span class="labelnoline">@file.LinkId</span></td>
                                </tr>
                                <tr class="doublespace">
                                    <td>
                                        Destination Country:
                                    </td>
                                    <td class="labelnoline">
                                        @file.Country.Name
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td colspan="3">
                                        Remarks: <span class="labelnoline">@file.Comments</span>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td>&nbsp;
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                                <tr class="doublespace">
                                    <td>
                                    </td>
                                    <td align="right">
                                        <table>
                                            <tr align="right">
                                                <td class="labelnoline">
                                                    @if(file.CertificateFee.HasValue)
                                                    {
                                                        <span>Certificate Fee = @string.Format("{0:C}", file.CertificateFee)</span>
                                                    }                                            
                                                </td>
                                            </tr>
                                            <tr align="right">
                                                <td class="labelnoline">
                                                    @if(file.OECDFee.HasValue)
                                                    {
                                                        <span>OECD Fee = @string.Format("{0:C}", file.OECDFee) </span>
                                                    }
                                                </td>
                                            </tr>
                                            <tr align="right">
                                                <td class="labelnoline">
                                                     @if(file.NotFinallyCertifiedFee.HasValue)
                                                    {
                                                        <span>Not Finally Certified Fee = @string.Format("{0:C}", file.NotFinallyCertifiedFee)</span>
                                                    }
                                                </td>
                                            </tr>
                                            <tr align="right">
                                                <td class="overline">
                                                     @if(file.NotFinallyCertifiedFee.HasValue)
                                                    {
                                                        <span class="labelnoline">Total Charges = @string.Format("{0:C}", file.TotalFee)</span>
                                                    }                                       
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                    <td>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3">&nbsp;
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
        </div>        
    }    
</body>

</html>

CCIA/Areas/Admin/Views/OECD/Lookup.cshtml
<h2>OECD</h2> 
<form asp-action="Details" method="GET">
<div class="container">
    <div class="row">
         <div class="col-sm-12">
            <div asp-validation-summary="All" class="text-danger"></div>            
        </div>  
    </div>
    <div class="form-group row required">
        <label for="Id" class="col-sm-3 col-form-label">OECD ID</label>
        <input type="text" id="Id" class="col-sm-9 form-control" name="Id" data-val="true" data-val-required="OECD ID is required" data-val-number="OECD ID must be a number.">
        <span class="field-validation-valid text-danger" for="Id"  data-valmsg-replace="true"></span>
    </div>
    <div class="row">
         <input type="submit" value="Get OECD File" id="submit" class="btn btn-primary"></input> |
         <a class="btn btn-dark" asp-action="Create" asp-controller="OECD" asp-area="Admin">Create new OECD</a>
    </div>
</div>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}