CCIA/Areas/Admin/Models/Organizations/ContactDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CCIA.Helpers;
using System.ComponentModel.DataAnnotations;
using CCIA.Services;

namespace CCIA.Models
{   
     
    public class AdminContactDetailsViewModel
    {
       public Contacts contact { get; set; }
       
       public List<Maps> maps { get; set; }

       
               
        public static async Task<AdminContactDetailsViewModel> Create(CCIAContext _dbContext, IFullCallService _helper, int id)
        {      
            
            var employee = await _helper.FullContact().Where(c => c.Id == id).FirstOrDefaultAsync();
            var orgMapPermissions = await _dbContext.OrgMaps.Where(p => p.OrgId == employee.OrgId).Select(p => p.Map).ToListAsync();

            var model = new AdminContactDetailsViewModel
            {
                contact = employee,
                maps = await _dbContext.Maps.Where(m => orgMapPermissions.Contains(m.Name)).OrderBy(m => m.Name).ToListAsync()
            };

            return model;
        }

        
    }    
    
}

CCIA/Areas/Admin/Models/Organizations/EditCreateAddressViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CCIA.Helpers;
using System.ComponentModel.DataAnnotations;
using CCIA.Services;

namespace CCIA.Models
{   
     
    public class AdminAddressEditCreateViewModel
    {
       public OrganizationAddress orgAddress {get; set;}

       public int OrgId { get; set; } 

       public string OrgName { get; set; }
        
       public List<Countries> countries { get; set; }

       public List<County> counties { get; set; }

       public List<StateProvince> states { get; set; }
               
        public static async Task<AdminAddressEditCreateViewModel> Create(CCIAContext _dbContext, int id, int orgId = 0)
        {
            var thisOrgAddress = await _dbContext.OrganizationAddress.Where(a => a.Id == id)
                .Include(a => a.Address)       
                .ThenInclude(a => a.Countries)
                .Include(oa => oa.Address)
                .ThenInclude(a => a.StateProvince)
                .Include(oa => oa.Address)
                .ThenInclude(a => a.County)
                .FirstOrDefaultAsync();                         

            var orgSearch = _dbContext.Organizations.Where(o => o.Id == thisOrgAddress.OrgId).AsQueryable();// .FirstOrDefaultAsync();
            if(orgId != 0)
            {
                orgSearch = _dbContext.Organizations.Where(o => o.Id == orgId).AsQueryable();
            }
            var org = await orgSearch.FirstOrDefaultAsync();
            var countyList = await _dbContext.County.Where(c => c.StateProvinceId == 102).OrderBy(x => x.Name).ToListAsync();
            countyList.Add(new County{CountyId = 0, Name= "Outside California"});
            if(thisOrgAddress == null && orgId != 0)
            {
                thisOrgAddress = new OrganizationAddress();
                thisOrgAddress.Address = new Address();
                thisOrgAddress.OrgId = orgId;
                thisOrgAddress.Address.StateProvinceId = await _dbContext.StateProvince.Where(s => s.Name == "California").Select(s => s.StateProvinceId).FirstOrDefaultAsync();
                thisOrgAddress.Address.CountryId = await _dbContext.Countries.Where(c => c.Name == "United States").Select(c => c.Id).FirstOrDefaultAsync();
            }
                       
            var model = new AdminAddressEditCreateViewModel
            {
                orgAddress = thisOrgAddress,                
                countries = await _dbContext.Countries.OrderBy(x => x.Name).ToListAsync(),
                counties = countyList,
                states = await _dbContext.StateProvince.OrderBy(x => x.Name).ToListAsync(),
                OrgId = org.Id, 
                OrgName = org.Name
            };

            return model;
        }

        
    }    
    
}

CCIA/Areas/Admin/Models/Organizations/EditCreateContactAddressViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CCIA.Helpers;
using System.ComponentModel.DataAnnotations;
using CCIA.Services;

namespace CCIA.Models
{   
     
    public class AdminContactAddressEditCreateViewModel
    {
       public ContactAddress address { get; set; } 

       public string ContactName { get; set; } 

       public int ContactId { get; set; }
        
       public List<Countries> countries { get; set; }

       public List<County> counties { get; set; }

       public List<StateProvince> states { get; set; }
               
        public static async Task<AdminContactAddressEditCreateViewModel> Create(CCIAContext _dbContext, int id, int contactId = 0)
        {       
             var thisAddress = await _dbContext.ContactAddress.Where(a => a.Id == id)
                .Include(c => c.Address)
                .ThenInclude(a => a.Countries)
                .Include(c => c.Address)
                .ThenInclude(a => a.StateProvince)
                .Include(c => c.Address)
                .ThenInclude(a => a.County)
                .FirstOrDefaultAsync();

            var countyList = await _dbContext.County.Where(c => c.StateProvinceId == 102).OrderBy(x => x.Name).ToListAsync();
            countyList.Add(new County{CountyId = 0, Name= "Outside California"});
            var contactSearch = _dbContext.Contacts.Where(c => c.Id == thisAddress.ContactId).AsQueryable();// .FirstOrDefaultAsync();
            if(contactId != 0)
            {
                contactSearch = _dbContext.Contacts.Where(c => c.Id == contactId).AsQueryable();
            } else
            {
                contactId = thisAddress.ContactId;
            }
            var contact = await contactSearch.Select(c => c.FirstName + ' ' + c.LastName).FirstOrDefaultAsync();
            
                       
            var model = new AdminContactAddressEditCreateViewModel
            {
                address = thisAddress,                
                countries = await _dbContext.Countries.OrderBy(x => x.Name).ToListAsync(),
                counties = countyList,
                states = await _dbContext.StateProvince.OrderBy(x => x.Name).ToListAsync(),                
                ContactName = contact,
                ContactId = contactId,
            };

            return model;
        }

        
    }    
    
}

CCIA/Areas/Admin/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CCIA.Models;
using Microsoft.AspNetCore.Authorization;
using CCIA.Services;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using CCIA.Helpers;
using System.Security.Cryptography;

namespace CCIA.Controllers
{
    [Authorize(Roles = "CoreStaff")]
    public class OrganizationsController : AdminController
    {

        // TODO Create org update in client area.
        private readonly CCIAContext _dbContext;
        private readonly IFullCallService _helper;
        private readonly INotificationService _notification;

        public OrganizationsController(CCIAContext dbContext, IFullCallService helper, INotificationService notificationService)
        {
            _dbContext = dbContext;
            _helper = helper;
            _notification = notificationService;
        }

        
        public async Task<IActionResult> Index(string term = "")
        {
            if(string.IsNullOrWhiteSpace(term))
            {
                return View(null);
            }
            
            var model = await _dbContext.Organizations
                .Include(o => o.Addresses.Where(a=> a.Active))
                .ThenInclude(o => o.Address)
                .ThenInclude(a => a.County)
                .Include(o => o.Addresses.Where(a=> a.Active))
                .ThenInclude(o => o.Address)
                .ThenInclude(a => a.StateProvince)
                .Where(o => EF.Functions.Like(o.Id.ToString(), "%" + term.Trim() + "%") || EF.Functions.Like(o.Name, "%" + term.Trim() + "%")).ToListAsync();

            return View(model);
        }

        [Authorize(Roles = "CoreStaff,Admin")]
        public async Task<IActionResult> InactiveEmployees(int id)
        {   
            var model = await _dbContext.Contacts.Where(c => c.OrgId == id && !c.Active).ToListAsync();
            return View(model);

        }

        public async Task<IActionResult> Details(int id)
        {
            var model = await AdminOrgDetailsViewModel.Create(_dbContext, _helper, id);            
            if(model.org == null)
            {
                return  RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create ()
        {
            var model = new Organizations();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Organizations org)
        {            
            var orgToCreate = new Organizations();            

            orgToCreate.Email = org.Email;
            orgToCreate.GermLab = org.GermLab;
            orgToCreate.Name = org.Name;
            orgToCreate.Phone = org.Phone;
            orgToCreate.Active = org.Active;
            orgToCreate.DiagnosticLab = org.DiagnosticLab;
            orgToCreate.Fax = org.Fax;
            orgToCreate.Website = org.Website;
            orgToCreate.AgCommissioner = org.AgCommissioner;
            orgToCreate.DateModified = DateTime.Now;
            orgToCreate.UserModified = User.FindFirstValue(ClaimTypes.Name);
            orgToCreate.MemberYear = 0;
            orgToCreate.Active = true;

             if(ModelState.IsValid){
                _dbContext.Add(orgToCreate);
                await _dbContext.SaveChangesAsync();
                Message = "Org Created";
            } else {
                ErrorMessage = "Something went wrong.";                
                return View(org); 
            }
            await _notification.OrgCreated(orgToCreate);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = orgToCreate.Id });  

        }

        [Authorize(Roles = "CoreStaff,Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _dbContext.Organizations.Include(o => o.Employees).Where(o => o.Id == id).FirstOrDefaultAsync();            
            if(model == null)
            {
                ErrorMessage = "Org not found!";
                return  RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "CoreStaff,Admin")]
        public async Task<IActionResult> Edit(int id, Organizations org)
        {
            var orgToUpdate = await _dbContext.Organizations.Where(o => o.Id == id).FirstOrDefaultAsync();
            if(orgToUpdate == null || orgToUpdate.Id != org.Id)
            {
                ErrorMessage = "Org not found!";
                return  RedirectToAction(nameof(Index));
            }
            

            orgToUpdate.Email = org.Email;
            orgToUpdate.GermLab = org.GermLab;
            orgToUpdate.Name = org.Name;
            orgToUpdate.Phone = org.Phone;
            orgToUpdate.Active = org.Active;
            orgToUpdate.DiagnosticLab = org.DiagnosticLab;
            orgToUpdate.Fax = org.Fax;
            orgToUpdate.Website = org.Website;
            orgToUpdate.AgCommissioner = org.AgCommissioner;
            orgToUpdate.DateModified = DateTime.Now;
            orgToUpdate.Notes = org.Notes;
            orgToUpdate.UserModified = User.FindFirstValue(ClaimTypes.Name);
            
            if(User.IsInRole("Admin"))
            {
                orgToUpdate.MemberType = org.MemberType;
                orgToUpdate.RepresentativeContactId = org.RepresentativeContactId;
            }
            

             if(ModelState.IsValid){
                await _dbContext.SaveChangesAsync();
                Message = "Org Updated";
            } else {
                ErrorMessage = "Something went wrong.";                
                return View(org); 
            }

            return RedirectToAction(nameof(Details), new { id = org.Id });  



        }

        [Authorize(Roles = "ConditionerStatusUpdate")]
        public async Task<IActionResult> EditStatus(int id)
        {
            var model = await _dbContext.CondStatus.Where(c => c.Id == id).FirstOrDefaultAsync();
            if(model == null)
            {
                ErrorMessage = "Status entry not found!";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ConditionerStatusUpdate")]
        public async Task<IActionResult> EditStatus(int id, CondStatus update)
        {
            var statusToUpdate = await _dbContext.CondStatus.Where(c => c.Id == id).FirstOrDefaultAsync();
            if(statusToUpdate == null || update == null || statusToUpdate.Id != update.Id)
            {
                ErrorMessage = "Status not found or not able to update";
                return RedirectToAction(nameof(Index));
            }

            statusToUpdate.Status = update.Status;
            statusToUpdate.AllowPretag = update.AllowPretag;
            statusToUpdate.PrintSeries = update.PrintSeries;
            statusToUpdate.RequestCciaPrintSeries = update.RequestCciaPrintSeries;
            statusToUpdate.DatePretagApproved = update.DatePretagApproved;
            statusToUpdate.DateUpdated = DateTime.Now;

            if(ModelState.IsValid){
                await _dbContext.SaveChangesAsync();
                Message = "Status Updated";
            } else {
                ErrorMessage = "Something went wrong.";                
                return View(update); 
            }

            return RedirectToAction(nameof(Details), new { id = statusToUpdate.OrgId });  
        }

        [Authorize(Roles = "ConditionerStatusUpdate")]
        public ActionResult NewStatus(int id)
        {
            var model = new CondStatus();
            model.OrgId = id;
            model.Year = CertYearFinder.ConditionerYear;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ConditionerStatusUpdate")]
        public async Task<IActionResult> NewStatus(int id, CondStatus newStatus)
        {
            var statusToCreate = new CondStatus();
            statusToCreate.Year = newStatus.Year;
            statusToCreate.Status = newStatus.Status;
            statusToCreate.AllowPretag = newStatus.AllowPretag;
            statusToCreate.PrintSeries = newStatus.PrintSeries;
            statusToCreate.RequestCciaPrintSeries = newStatus.RequestCciaPrintSeries;
            statusToCreate.DatePretagApproved = newStatus.DatePretagApproved;
            statusToCreate.DateUpdated = DateTime.Now;
            statusToCreate.OrgId = newStatus.OrgId;

             if(ModelState.IsValid){
                 _dbContext.Add(statusToCreate);
                await _dbContext.SaveChangesAsync();
                Message = "Status Created";
            } else {
                ErrorMessage = "Something went wrong.";                
                return View(newStatus); 
            }

            return RedirectToAction(nameof(Details), new { id = newStatus.OrgId }); 
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddAddress(int id)
        {
            var model = await AdminAddressEditCreateViewModel.Create(_dbContext, 0, id);
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddAddress(int id, AdminAddressEditCreateViewModel vm)
        {
            var addressToAdd = new OrganizationAddress();
            addressToAdd.Address = new Address();
            var newAddress = vm.orgAddress;
            if(newAddress.Address.CountyId == 0 && newAddress.Address.StateProvinceId == 102)
            {

CCIA/Areas/AgComm/Views/Organization/AddAddress.cshtml
@model CCIA.Models.AdminAddressEditCreateViewModel

<form asp-action="AddAddress">
@Html.HiddenFor(x => x.OrgId)
<div class="container col-sm-12">    
    <div class="row">
        <div class="col-sm-12">
            <h2>Edit Address for @Model.OrgName</h2> 
        </div>            
    </div>
    <div class="row">
         <div class="col-sm-12">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>  
    </div>  
    <div class="col-sm-8">
        <div class="form-group row">                
            <label asp-for="orgAddress.Mailing" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Mailing" class="col-sm-1 form-control">
        </div>
        <div class="form-group row">                
            <label asp-for="orgAddress.Billing" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Billing" class="col-sm-1 form-control">
        </div>
        <div class="form-group row">                
            <label asp-for="orgAddress.Delivery" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Delivery" class="col-sm-1 form-control">
        </div> 
        <div class="form-group row">                
            <label asp-for="orgAddress.Physical" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Physical" class="col-sm-1 form-control">
        </div> 
        <div class="form-group row">                
            <label asp-for="orgAddress.Facility" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Facility" class="col-sm-1 form-control">
        </div> 
        <div class="form-group row">
            <label asp-for="orgAddress.Address.Address1" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.Address1" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.Address1" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group row">
            <label asp-for="orgAddress.Address.Address2" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.Address2" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.Address2" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group row">
            <label asp-for="orgAddress.Address.Address3" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.Address3" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.Address3" data-valmsg-replace="true"></span>
        </div> 
        <div class="form-group row">
            <label asp-for="orgAddress.Address.City" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.City" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.City" data-valmsg-replace="true"></span>
        </div>  
        <div class="form-group row">
            <label asp-for="orgAddress.Address.CountyId" class="col-sm-3 col-form-label">County</label>
            <select required asp-for="orgAddress.Address.CountyId" class="col-sm-5 form-control" asp-items="@(new SelectList(Model.counties, "CountyId", "Name"))"></select>
        </div>
       <div class="form-group row">
            <label asp-for="orgAddress.Address.StateProvinceId" class="col-sm-3 col-form-label">State</label>
            <select required asp-for="orgAddress.Address.StateProvinceId" class="col-sm-5 form-control" asp-items="@(new SelectList(Model.states, "StateProvinceId", "Name"))"></select>
        </div>   
        <div class="form-group row">
            <label asp-for="orgAddress.Address.CountryId" class="col-sm-3 col-form-label">Country</label>
            <select required asp-for="orgAddress.Address.CountryId" class="col-sm-5 form-control" asp-items="@(new SelectList(Model.countries, "Id", "Name"))"></select>
        </div> 
        <div class="form-group row">
            <label asp-for="orgAddress.Address.PostalCode" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.PostalCode" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.PostalCode" data-valmsg-replace="true"></span>
        </div>
        <div class="row">
         <div class="col-sm-12">             
            <input type="submit" value="Update" class="btn btn-primary"></input>   
            <a class="btn btn-dark" asp-action="Details" asp-controller="Organizations" asp-area="Admin" asp-route-id="@Model.OrgId">Cancel Add</a>
        </div>
    </div>
</div>
</form>

@section Scripts {
     @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}  
    
}

CCIA/Areas/AgComm/Views/Organization/DeleteAddress.cshtml
@model CCIA.Models.OrganizationAddress

<form asp-action="ConfirmDeleteAddress">
@Html.HiddenFor(x => x.Id)
<input type="hidden" id="Delete" name="Delete" value="Delete">
<div class="container col-sm-12">    
    <div class="row">
        <div class="col-sm-12">
            <h2>Confirm Delete this Address?</h2> 
        </div>            
    </div>    
    <div class="col-sm-6">
        <div class="form-group row">                
            <label asp-for="Mailing" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="Mailing" class="col-sm-1 form-control">
        </div>
        <div class="form-group row">                
            <label asp-for="Billing" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="Billing" class="col-sm-1 form-control">
        </div>
        <div class="form-group row">                
            <label asp-for="Delivery" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="Delivery" class="col-sm-1 form-control">
        </div> 
        <div class="form-group row">                
            <label asp-for="Physical" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="Physical" class="col-sm-1 form-control">
        </div>   
        <div class="form-group row">
            <label asp-for="Address.Address1" class="col-sm-3 col-form-label"></label>
            <input asp-for="Address.Address1" class="col-sm-3 form-control">
        </div>
        <div class="form-group row">
            <label asp-for="Address.Address2" class="col-sm-3 col-form-label"></label>
            <input asp-for="Address.Address2" class="col-sm-3 form-control">
        </div>
        <div class="form-group row">
            <label asp-for="Address.Address3" class="col-sm-3 col-form-label"></label>
            <input asp-for="Address.Address3" class="col-sm-3 form-control">
        </div> 
        <div class="form-group row">
            <label asp-for="Address.City" class="col-sm-3 col-form-label"></label>
            <input asp-for="Address.City" class="col-sm-3 form-control">
        </div>          
        <div class="form-group row">
            <label asp-for="Address.PostalCode" class="col-sm-3 col-form-label"></label>
            <input asp-for="Address.PostalCode" class="col-sm-3 form-control">
        </div>
        <div class="row">
         <div class="col-sm-12">             
            <input type="submit" value="Delete" class="btn btn-danger"></input>   
            <a class="btn btn-dark" asp-action="Details" asp-controller="Organizations" asp-area="Admin" asp-route-id="@Model.OrgId">Cancel Deletion</a>
        </div>
    </div>
</div>
</form>

CCIA/Areas/AgComm/Views/Organization/EditAddress.cshtml
@model CCIA.Models.AdminAddressEditCreateViewModel

<form asp-action="EditAddress">
@Html.HiddenFor(x => x.orgAddress.Address.Id)
@Html.HiddenFor(x => x.OrgId)
@Html.HiddenFor(x => x.orgAddress.Active)
<div class="container col-sm-12">    
    <div class="row">
        <div class="col-sm-12">
            <h2>Edit Address for @Model.OrgName</h2> 
        </div>            
    </div>
    <div class="row">
         <div class="col-sm-12">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>  
    </div>  
    <div class="col-sm-8">
        <div class="form-group row">                
            <label asp-for="orgAddress.Mailing" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Mailing" class="col-sm-1 form-control">
        </div>
        <div class="form-group row">                
            <label asp-for="orgAddress.Billing" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Billing" class="col-sm-1 form-control">
        </div>
        <div class="form-group row">                
            <label asp-for="orgAddress.Delivery" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Delivery" class="col-sm-1 form-control">
        </div> 
        <div class="form-group row">                
            <label asp-for="orgAddress.Physical" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Physical" class="col-sm-1 form-control">
        </div> 
        <div class="form-group row">                
            <label asp-for="orgAddress.Facility" class="col-sm-3 col-form-label"></label>
            <input type="checkbox" asp-for="orgAddress.Facility" class="col-sm-1 form-control">
        </div>   
        <div class="form-group row">
            <label asp-for="orgAddress.Address.Address1" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.Address1" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.Address1" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group row">
            <label asp-for="orgAddress.Address.Address2" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.Address2" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.Address2" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group row">
            <label asp-for="orgAddress.Address.Address3" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.Address3" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.Address3" data-valmsg-replace="true"></span>
        </div> 
        <div class="form-group row">
            <label asp-for="orgAddress.Address.City" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.City" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.City" data-valmsg-replace="true"></span>
        </div>  
        <div class="form-group row">
            <label asp-for="orgAddress.Address.CountyId" class="col-sm-3 col-form-label">County</label>
            <select required asp-for="orgAddress.Address.CountyId" class="col-sm-5 form-control" asp-items="@(new SelectList(Model.counties, "CountyId", "Name"))"></select>
        </div>
       <div class="form-group row">
            <label asp-for="orgAddress.Address.StateProvinceId" class="col-sm-3 col-form-label">State</label>
            <select required asp-for="orgAddress.Address.StateProvinceId" class="col-sm-5 form-control" asp-items="@(new SelectList(Model.states, "StateProvinceId", "Name"))"></select>
        </div>   
        <div class="form-group row">
            <label asp-for="orgAddress.Address.CountryId" class="col-sm-3 col-form-label">Country</label>
            <select required asp-for="orgAddress.Address.CountryId" class="col-sm-5 form-control" asp-items="@(new SelectList(Model.countries, "Id", "Name"))"></select>
        </div> 
        <div class="form-group row">
            <label asp-for="orgAddress.Address.PostalCode" class="col-sm-3 col-form-label"></label>
            <input asp-for="orgAddress.Address.PostalCode" class="col-sm-3 form-control">
            <span class="field-validation-valid text-danger" data-valmsg-for="orgAddress.Address.PostalCode" data-valmsg-replace="true"></span>
        </div>
        <div class="row">
         <div class="col-sm-12">             
            <input type="submit" value="Update" class="btn btn-primary"></input>   
            <a class="btn btn-dark" asp-action="Details" asp-controller="Organizations" asp-area="Admin" asp-route-id="@Model.OrgId">Cancel Edit</a>
        </div>
    </div>
</div>
</form>

@section Scripts {
     @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}  
    
}