CCIA/Models/Maps.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace CCIA.Models
{
    public partial class Maps
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Url { get; set; }
    }
}

CCIA/Areas/Admin/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCIA.Helpers;
using CCIA.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CCIA.Models.IndexViewModels;
using CCIA.Models.DetailsViewModels;
using System.Security.Claims;
using CCIA.Services;
using Microsoft.Data.SqlClient;
using System.IO;
using CCIA.Models.ApplicationViewModels;

namespace CCIA.Controllers.Admin
{

    public class ApplicationController : AdminController
    {
        private readonly CCIAContext _dbContext;

        private readonly IFullCallService _helper;

        private readonly INotificationService _notificationService;

              

        private readonly IFileIOService _fileService;

        public ApplicationController(CCIAContext dbContext, IFullCallService helper, INotificationService notificationService,IFileIOService fileIOService)
        {
            _dbContext = dbContext;
            _helper = helper;
            _notificationService = notificationService;
            _fileService = fileIOService;            
        }

        
        public async Task<IActionResult> Index(int certYear)
        {            
            if (certYear == 0)
            {
                certYear = await _dbContext.Applications.MaxAsync(a => a.CertYear);
            }
            var model = await AdminApplicationIndexViewModel.Create(_dbContext, certYear, false, _helper);
            return View(model);
        }

         public async Task<IActionResult> Pending()
        {   var model = await _helper.OverviewApplications().Where(a => a.Status == ApplicationStatus.PendingAcceptance.GetDisplayName()).ToListAsync();
            ViewBag.HideFI = "True";

            return View(model);
        }

         public async Task<IActionResult> Accepted(int certYear)
        {            
            if (certYear == 0)
            {
                certYear = await _dbContext.Applications.MaxAsync(a => a.CertYear);
            }
             ViewBag.AcresApproved = "Yes";
            var model = await AdminApplicationIndexViewModel.Create(_dbContext, certYear, true, _helper);
            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateComments (int Id, string comments )
        {
            comments = comments?.Trim();
            var appToUpdate = await _dbContext.Applications.Where(a => a.Id == Id).FirstOrDefaultAsync();
            if(appToUpdate == null)
            { 
                ErrorMessage = "Application not found.";
                return RedirectToAction(nameof(Index));
            }
            appToUpdate.Comments = comments;
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = Id }); 
        }

        public async Task<IActionResult> EditSite(int id)
        {
            var model = await NativeSeedSiteEditModel.EditModel(_dbContext, id);
            if (model.Site == null)
            {
                ErrorMessage = "Site not found!";
                return RedirectToAction(nameof(Index));
            }
            var app = await _dbContext.Applications.Where(a => a.Id == model.Site.AppId).FirstOrDefaultAsync();
            if (app == null)
            {
                ErrorMessage = "Site Application not found!";
                return RedirectToAction(nameof(Index));
            }           
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditSite(int id, NativeSeedSiteEditModel vm)
        {
            var siteToUpdate = await _dbContext.NativeSeedSites.Where(s => s.Id == vm.Site.Id).FirstOrDefaultAsync();
            if (siteToUpdate == null)
            {
                ErrorMessage = "Site not found!";
                return RedirectToAction(nameof(Index));
            }
            var app = await _dbContext.Applications.Where(a => a.Id == siteToUpdate.AppId).FirstOrDefaultAsync();
            if (app == null)
            {
                ErrorMessage = "Site Application not found!";
                return RedirectToAction(nameof(Index));
            }            
            var updatedSite = vm.Site;
            siteToUpdate.SiteName = updatedSite.SiteName;
            siteToUpdate.CollectionAreaSize = updatedSite.CollectionAreaSize;
            siteToUpdate.FieldElevation = updatedSite.FieldElevation;
            siteToUpdate.Lat = updatedSite.Lat;
            siteToUpdate.Long = updatedSite.Long;
            siteToUpdate.SiteCounty = updatedSite.SiteCounty;
            siteToUpdate.HarvestDate = updatedSite.HarvestDate;
            siteToUpdate.Comments = updatedSite.Comments;

            if (ModelState.IsValid)
            {
                await _dbContext.SaveChangesAsync();
                Message = "Site Updated";
            }
            else
            {
                ErrorMessage = "Something went wrong.";
                var model = await NativeSeedSiteEditModel.EditModel(_dbContext, id);
                return View(model);
            }

            return RedirectToAction(nameof(Details), new { id = siteToUpdate.AppId });

        }

        public async Task<IActionResult> NewSite(int id)
        {
            var model = await NativeSeedSiteEditModel.CreateModel(_dbContext, id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> NewSite(int id, NativeSeedSiteEditModel vm)
        {
            var siteToCreate = new NativeSeedSites();
            var app = await _dbContext.Applications.Where(a => a.Id == vm.Site.AppId).FirstOrDefaultAsync();
            if (app == null || id != vm.Site.AppId)
            {
                ErrorMessage = "Site Application not found!";
                return RedirectToAction(nameof(Index));
            }            
            var submittedSite = vm.Site;
            siteToCreate.SiteName = submittedSite.SiteName;
            siteToCreate.AppId = submittedSite.AppId;
            siteToCreate.CollectionAreaSize = submittedSite.CollectionAreaSize;
            siteToCreate.FieldElevation = submittedSite.FieldElevation;
            siteToCreate.Lat = submittedSite.Lat;
            siteToCreate.Long = submittedSite.Long;
            siteToCreate.SiteCounty = submittedSite.SiteCounty;
            siteToCreate.HarvestDate = submittedSite.HarvestDate;
            siteToCreate.Comments = submittedSite.Comments;

            if (ModelState.IsValid)
            {
                _dbContext.Add(siteToCreate);
                await _dbContext.SaveChangesAsync();
                Message = "Site Created";
            }
            else
            {
                ErrorMessage = "Something went wrong.";
                var model = await NativeSeedSiteEditModel.CreateModel(_dbContext, id);
                return View(model);
            }

            return RedirectToAction(nameof(Details), new { id = siteToCreate.AppId });
        }

        public async Task<IActionResult> NewMap(int id)
        {
            var model = await NewMapViewModel.Create(_dbContext, id);           
            if(model.application == null)
            {
                ErrorMessage = "App not found!";
                return  RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> NewMap(int id, string map, string updateBoth)
        {
            var points = new SqlParameter("points", map);
            var msg = new SqlParameter
            {
                ParameterName = "msg",
                SqlDbType = System.Data.SqlDbType.VarChar,
                Direction = System.Data.ParameterDirection.Output,
                Size = 100,
            };
            await _dbContext.Database.ExecuteSqlRawAsync($"EXEC mvc_map_app_validate_field @points, @msg output", points, msg); 
            if(msg.Value.ToString() != "Ok")
            {
                switch(msg.Value.ToString()){
                    case "Not valid":
                        ErrorMessage = "Field not valid. This most commonly is because the external boundary of the field crosses itself. Please redraw field.";
                        break;
                    case "Ring orientation":
                        ErrorMessage = "Field area is quite large. This most commonly is because the field was drawn in the wrong direction. Please redraw field; ensure you draw in a clockwise direction (start at north west corner, then move east).";
                        break;
                };
                var model = await NewMapViewModel.Create(_dbContext, id);           
                if(model.application == null)
                {
                    ErrorMessage = "App not found!";
                    return  RedirectToAction(nameof(Index));
                }
                return View(model);
            }

            var appId = new SqlParameter("app_id", id);
            var link = new SqlParameter("link", updateBoth == "on" ? true : false);
            
            await _dbContext.Database.ExecuteSqlRawAsync($"EXEC mvc_insert_app_map @app_Id, @points, @link", appId, points, link); 
            Message = "Field Updated";
            return RedirectToAction(nameof(Details), new { id = id }); 
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AcceptApplication(IFormCollection form)
        {
            var id = int.Parse(form["application.Id"].ToString());
            var appToAccept = await _dbContext.Applications.Where(a => a.Id == id).FirstAsync();
            appToAccept.Status = ApplicationStatus.FieldInspectionInProgress.GetDisplayName();
            appToAccept.Approved = true;
            appToAccept.DateApproved = DateTime.Now;            
            appToAccept.Approver = User.FindFirstValue(ClaimTypes.Name);

CCIA/Areas/Admin/Controllers/MapController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CCIA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;
using Newtonsoft.Json;

namespace CCIA.Controllers.Admin
{
   
    public class MapController : AdminController
    {
        private readonly CCIAContext _dbContext;

        public MapController(CCIAContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<JsonResult> GetFIRSeachObjects(int time,string ids, string geoType)
        {
            var appIds = ids.Split(',').Select(x => int.Parse(x)).ToList();
            var pins = await _dbContext.Applications.Where(a => appIds.Contains(a.Id))
                .Include(a => a.ApplicantOrganization)
                .Include(a => a.Crop)
                .Include(a => a.Variety)
                .Include(a => a.ClassProduced)
                .Select(a => new MapWKT{ Title= "AppId: " + a.Id.ToString(), GeoField = geoType == "point" ? a.GeoField.Centroid.AsText() : a.GeoField.AsText() , GeoType = geoType,  Description = 
                    $"App: {a.ApplicantOrganization.NameAndId}<br>Crp: {a.Crop.Name}<br>Var: {a.Variety.Name}<br>Cl: {a.ClassProduced.ClassProducedTrans}>br>Fld: {a.FieldName}<br>Pt dt: {a.DatePlanted.Value.ToShortDateString()}<br>" +
                    $"<a href='/admin/Application/FieldMap/{a.Id}'>Map</a><br/><a href='admin/Application/Fir/{a.Id}'>FIR</a>"})
                .ToListAsync();
            return Json(pins);
        }             
       
    }
}

CCIA/Areas/AgComm/Controllers/ApplicationsController.cs
using System.Linq;
using System.Threading.Tasks;
using CCIA.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CCIA.Services;
using CCIA.Models.DetailsViewModels;
using CCIA.Helpers;

namespace CCIA.Controllers.AgComm
{


    public class ApplicationsController : AgCommController
    {
        private readonly CCIAContext _dbContext;
        private readonly IFullCallService _helper;
        private readonly IFileIOService _fileService;

        public ApplicationsController(CCIAContext dbContext, IFullCallService helper,IFileIOService fileIOService)
        {
            _dbContext = dbContext;
            _helper = helper;
            _fileService = fileIOService;

        }

        public async Task<IActionResult> Index(int id, AgCommSearchViewModel vm)
        {
            var orgId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value);
            var countyId = await _dbContext.Organizations.Where(o => o.Id == orgId).Select(o => o.CountyId).FirstAsync();
            if(!countyId.HasValue)
            {
                countyId = 0;
            }
            if(!vm.Search){
                var freshmodel = await AgCommSearchViewModel.Create(_dbContext, null, _helper, countyId.Value);
                return View(freshmodel);  
            }
                var model = await AgCommSearchViewModel.Create(_dbContext, vm, _helper, countyId.Value);
                
                return View(model);            
        }  

        // GET: Application/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var orgId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value);
            var countyId = await _dbContext.Organizations.Where(o => o.Id == orgId).Select(o => o.CountyId).FirstAsync();
            if(!countyId.HasValue)
            {
                countyId = 0;
            }
            var seedTransferApps = await _dbContext.SeedTransfers.Where(s => s.ApplicationId.HasValue && s.ApplicationId.Value == id && s.PurchaserCountyId == countyId).AnyAsync();
            var model = await _dbContext.Applications.Where(a => a.Id == id && (a.FarmCounty == countyId || seedTransferApps))
                .Include(a => a.GrowerOrganization)
                .Include(a => a.ApplicantOrganization)
                .Include(a => a.County)
                .Include(a => a.Crop)
                .Include(a => a.Variety)
                .Include(a => a.ClassProduced)
                .Include(a => a.AppTypeTrans)
                .Include(a => a.Certificates)
                .Include(a => a.PlantingStocks)
                .ThenInclude(p => p.PsClassNavigation)
                .Include(a => a.PlantingStocks).ThenInclude(p => p.GrownStateProvince)
                .Include(a => a.PlantingStocks).ThenInclude(p => p.TaggedStateProvince)
                .Include(a => a.PlantingStocks).ThenInclude(p => p.GrownCountry)
                .Include(a => a.PlantingStocks).ThenInclude(p => p.TaggedCountry)
                .Include(a => a.FieldHistories).ThenInclude(fh => fh.FHCrops)
                .FirstOrDefaultAsync();

            if(model == null)
            {
                ErrorMessage = "That app was either not found or does not belong to your organization.";
                return  RedirectToAction(nameof(Index));
            }    
            return View(model);
        }

        
        public async Task<IActionResult> FieldMap(int id)
        {
            var model = await AdminMapFieldsViewModel.SingleMap(_dbContext, id, _helper);
            var orgId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value);
            var countyId = await _dbContext.Organizations.Where(o => o.Id == orgId).Select(o => o.CountyId).FirstAsync();
            if(!countyId.HasValue)
            {
                countyId = 0;
            }
            if(model.details.application.FarmCounty != countyId)
            {
                ErrorMessage = "That app does not belong in your county.";
                return  RedirectToAction(nameof(Index));
            }
            return View(model);  
        }

        
        public async Task<IActionResult> GetCertificateFile(int id, string link)
        {
            var app = await _dbContext.Applications.Where(a => a.Id == id).FirstOrDefaultAsync();
            
            if(app == null)
            {
                ErrorMessage = "App not found";
                return RedirectToAction(nameof(Index));
            }
            var orgId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "orgId").Value);
            var countyId = await _dbContext.Organizations.Where(o => o.Id == orgId).Select(o => o.CountyId).FirstAsync();
            if(!countyId.HasValue)
            {
                countyId = 0;
            }
            if(app.FarmCounty != countyId)
            {
            
                ErrorMessage = "That app does not belong in your county.";
                return  RedirectToAction(nameof(Index));
            }
            var contentType = "APPLICATION/octet-stream";
            return File(_fileService.DownloadCertificateFile(app, link), contentType, link);
        }

         public async Task<ActionResult> FIRCertificate(int id)
        {
            var model = await AdminViewModel.CreateFIR(_dbContext, id, _helper);
            if(model.application.AppType == AppTypes.Potato.GetDisplayName())
            {
                return View("~/Areas/Admin/Views/Application/FIRCertificatePotato.cshtml", model);
            }            
            return View("~/Areas/Admin/Views/Application/FIRCertificate.cshtml",model);
        }
    }
}

CCIA/Areas/AgComm/Views/Applications/Details.cshtml
@model CCIA.Models.Applications
@using CCIA.Helpers;
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
 
@{
    bool showPurchasedFrom = false;
    bool showPounds = false;
    bool showPlantsPerAcre = false;
    bool showTHC = false;
}

<h2>Application Details</h2> 
<div class="container">
     @if(Model.Status == "Field Inspection Report Ready")
    {
       <div class="row">
           <div class="col-sm-12"><hr></div>
            <div class="col-sm-12">
                <a class="btn btn-info" asp-action="FIRCertificate" asp-route-id="@Model.Id">Field Inspection Report</a>                
            </div>
            <div class="col-sm-12"><hr></div>
        </div>
    }
    <div class="row">
        <div class="col-lg-6">
                <div class="form-group row">
                    <label asp-for="Id" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.Id)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Status" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.Status)
                    </div>
                </div>                
                <div class="form-group row">
                    <label asp-for="ApplicantOrganization.NameAndId" class="col-sm-3 col-form-label">Applicant</label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.ApplicantOrganization.NameAndId)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Crop.Name" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.Crop.Name)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ClassProduced.ClassProducedTrans" class="col-sm-3 col-form-label">Class</label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.ClassProduced.ClassProducedTrans)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="MapVe" class="col-sm-3 col-form-label"></label>
                    <input type="checkbox" asp-for="MapVe" class="col-sm-3 form-control">   
                    @if(Model.MapVe)
                    {
                        <div>
                            <a class="btn btn-info" asp-action="FieldMap" asp-controller="Applications" asp-route-id="@Model.Id">View Map</a>
                        </div>  
                    }                 
                </div>                 
                <div class="form-group row">
                    <label asp-for="FieldName" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.FieldName)
                    </div>
                </div>
        </div>
        <div class="col-lg-6">
                <div class="form-group row">
                    <label asp-for="CertYear" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.CertYear)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="AppType" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.AppTypeTrans.AppTypeTrans)
                    </div>
                </div>               
                <div class="form-group row">
                    <label asp-for="GrowerOrganization.NameAndId" class="col-sm-3 col-form-label">Grower</label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.GrowerOrganization.NameAndId)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Variety.Name" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.Variety.Name)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="AcresApplied" class="col-sm-3 col-form-label">Acres</label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.AcresApplied) 
                        @if(Model.IsSquareFeet)
                        {
                            <span>Square feet</span>
                        } 
                        (Mapped: @Html.DisplayFor(x => x.AreaAcres) )
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="DatePlanted" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.DatePlanted)
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="County.Name" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 form-control-plaintext">
                        @Html.DisplayFor(x => x.County.Name)
                    </div>
                </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="col-lg-1 row">
         <h3>Certificates/Tags</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var row in Model.Certificates)
                    {
                        <tr>
                            <td>@row.Name</td>
                            <td>
                               <a asp-action=GetCertificateFile asp-route-id="@Model.Id" asp-route-link="@row.Link">@row.Link</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            <hr />
        </div>
    <hr>
    @if(Model.PlantingStocks.Any())
    {
    <div class="row">
        <label class="col-form-label">Planting Stock Info</label>
        <table class="table">
            <thead>
                <tr>
                    <th>Cert#</th>
                    <th>Variety</th>
                    @if(Model.PlantingStocks.First().PoundsPlanted != null || Model.PlantingStocks.Last().PoundsPlanted != null)
                    {
                        showPounds = true;
                        <th>Pounds Planted</th>
                    } 
                    @if(Model.PlantingStocks.First().PlantsPerAcre != null || Model.PlantingStocks.Last().PlantsPerAcre != null)
                    { 
                        showPlantsPerAcre = true;                       
                        <th>Plants/Acre</th>
                    }                 
                    <th>Class</th>
                    <th>Tag Issued</th>
                    <th>Grown</th>
                    @if(Model.PlantingStocks.First().SeedPurchasedFrom != null || Model.PlantingStocks.Last().SeedPurchasedFrom != null)
                    {
                        showPurchasedFrom = true;
                        <th>Purchased From</th>
                    } 
                    @if(Model.AppType == "PO")
                    {
                        <th>Winter test?</th>
                        <th>PVX test?</th>
                    }
                    @if(Model.PlantingStocks.First().ThcPercent != null || Model.PlantingStocks.Last().ThcPercent != null)
                    {
                        showTHC = true;
                        <th>THC%</th>
                    } 
                </tr>
            </thead>
            <tbody>
                @foreach (var row in Model.PlantingStocks.OrderBy(p => p.PsId))
                {
                    <tr>
                        <td>
                            @row.PsCertNum
                        </td>
                        <td>@row.PsEnteredVariety</td>
                        @if(showPounds)
                        {
                            <td>@Html.DisplayFor(x => row.PoundsPlanted)</td>
                        }
                        @if(showPlantsPerAcre)
                        {
                            <td>@row.PlantsPerAcre</td>
                        }                        
                        <td>@if(row.PsClassNavigation != null)
                            {@row.PsClassNavigation.ClassProducedTrans
                                @if(row.PsAccession != null){
                                    <span>- @row.PsAccession</span>
                                }
                            }
                        </td>
                         @if(@row.TaggedStateProvince != null)
                        {
                            <td>@row.TaggedStateProvince.Name</td>
                        } else if(@row.TaggedCountry != null){
                            <td>@row.TaggedCountry.Name</td>
                        } else {
                            <td>???</td>
                        }
                        @if(@row.GrownStateProvince != null && @row.GrownStateProvince.Name != null)
                        {
                            <td>@row.GrownStateProvince.Name</td>
                        }  else if(@row.GrownCountry != null) 
                        {
                            <td>@row.GrownCountry.Name</td>
                        } else {
                            <td>???</td>
                        }                                                              
                        @if(showPurchasedFrom)
                        {
                            <td>@row.SeedPurchasedFrom</td>
                        }                        
                        @if(Model.AppType == "PO")
                        {
                            <td>@Html.DisplayFor(x => row.WinterTest)</td>
                            <td>@Html.DisplayFor(x => row.PvxTest)</td>
                        }
                        @if(showTHC)
                        {
                            <td>@row.ThcPercent</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
    }
    <div class="row">
        <hr />
    </div>  
    <div class="row">
        <label class="col-form-label">Field History</label>
        <table class="table">
            <thead>
            <tr>
                <th>Year</th>
                <th>Crop</th>
                <th>Variety</th>
                <th>Application #</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var row in Model.FieldHistories.OrderBy(h => h.Year))
            {
                <tr>                    
                    <td>@row.Year</td>
                    <td>@(@row.FHCrops == null ? "" : @row.FHCrops.Name)</td>
                    <td>@row.Variety</td>
                    <td>@row.AppNumber</td>
                </tr>
            }
            </tbody>
        </table>
    </div>  
</div>


@section Scripts {
    <script type="text/javascript">
        $(document).ready(
            function(){
                $('input:file').change(
                    function(){
                        if ($(this).val()) {
                            $('input:submit').removeAttr('disabled'); 
                        } 
                    }
                );
            $(":checkbox").on("click", false);
        });
    </script>
   
}

CCIA/Areas/AgComm/Views/Applications/FieldMap.cshtml
@model CCIA.Models.AdminMapFieldsViewModel

<div class="row">
    <a class="btn btn-info" asp-action="Details" asp-controller="Applications" asp-route-id="@Model.details.application.Id">Return to Details</a>
</div> 

<div class="col-sm-12">
    <div class="container">
        @{await Html.RenderPartialAsync("_Map", Model);}
    </div>
</div>

@section Scripts {
    <script type='text/javascript' src="//www.bing.com/api/maps/mapcontrol?callback=loadMapScenario" async defer></script>
    <script type="text/javascript" src="/js/Maps/MapFieldsV8.js"></script>
}

CCIA/Areas/AgComm/Views/Applications/_Map.cshtml
@model CCIA.Models.AdminMapFieldsViewModel

<div class="container">
    
    <div id="MapDiv" style="position:relative;width:800px;height:600px;float:left; z-index: 1">
        <div id="myMap" style="position:relative; width:100%;height:90vh;"></div>        
    </div>    
</div>

<input type="hidden" id="data" value="@Model.data">